export const dynamic = 'force-dynamic';
import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import Header from '@/components/custom/header';
import StoreProvider from './StoreProvider';
import { Toaster } from '@/components/ui/toaster';
import Refresher from '@/components/custom/refresher';
import QueryProvider from './QueryProvider';


const manrope = Manrope({ subsets: ['latin'], variable: '--font-manrope' });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <StoreProvider>
                <body
                    className={cn(
                        'min-h-screen bg-background font-manrope antialiased',
                        manrope.variable
                    )}>
                    <QueryProvider>
                        {/* <Refresher> */}
                            <Header />
                            {/* Demo Banner */}
                            <div className="bg-amber-400 text-black text-center py-2 px-4 text-sm font-medium sticky top-0 z-50">
                                &#9888; Backend is currently offline.{' '}
                                
                                    <a href="https://youtu.be/7h4t78EJLWo?si=BVcRmvuBDffwcjo9"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="font-bold underline">
                                    Watch the full demo here &rarr;
                                </a>
                            </div>
                            <main>{children}</main>
                            <Toaster />
                        {/* </Refresher> */}
                    </QueryProvider>
                </body>
            </StoreProvider>
        </html>
    );
}
